### ISSUE TITLE
Fix missing Utils\HTTP object

### ISSUE THREAD

**Issue by Schneydr** [simplesamlphp/simplesamlphp-module-memcookie#13]
The Utils\HTTP object is never inititalised resulting in an error when access it in Memcookie.php, line 115.
See my pull request to solve this issue: https://github.com/Schneydr/simplesamlphp-module-memcookie/tree/Schneydr-patch-1

**Comment by tvdijen** [comment]
Fixed in ecea7bde27b32c2f5ebe532e57527279a447e489 and tagged v1.3.2
Thanks @Schneydr !
