### ISSUE TITLE
Error in www/auth.php

### ISSUE THREAD

**Issue by hikarukujo** [simplesamlphp/simplesamlphp-module-memcookie#5]
Followed along with the instructions, all seems to be good except I throw the following error when using /simplesaml/module.php/memcookie/auth.php as the 401 location for my site:
PHP Fatal error:  Cannot declare class SimpleSAML_Configuration, because the name is already in use in /REMOVED/simplesamlphp/lib/SimpleSAML/Configuration.php on line 11

The xdebug output puts the error at "$ssp_cf = \SimpleSAML\Configuration::getInstance();" on line 16 of www/auth.php in the module, not sure why it thinks the class is being declared a second time. Any ideas?

**Comment by hikarukujo** [comment]
![xdebug](https://user-images.githubusercontent.com/5297911/53210796-b4a51e80-3604-11e9-8e1f-54194dfb5713.jpg)
Output from the xdebug module.

**Comment by tvdijen** [comment]
Hi @hikarukujo!

My guess is that you're trying to use this module on 1.16.x, am I right?
I was a bit early releasing v1.2 of the module.. It works on 1.17 only..
Can you confirm?

**Comment by hikarukujo** [comment]
That seemed to help a lot, it's responding and authenticating. Now, though, I get a "page not found" loading when I attempt to access my protected directory.

`SimpleSAML\Error\NotFound: The requested page 'https://REDACTED/directory' could not be found. The URL must at least contain a module name followed by a slash.`

I have simplesamlphp setup as an alias in Apache so it's not hosted in the root directory of the site, per best-practice, but does my protected directory need to be somewhere else, too? I have it in the root directory of the site on the filesystem right now. Not sure if this is a simplesamlphp issue or one with the memcookie plugin right now.

**Comment by tvdijen** [comment]
It's hard to tell with so little information...
Apparently accessing a protected directory is triggering a redirect to SimpleSAMLphp, but to the wrong location..

**Comment by hikarukujo** [comment]
So my site config in apache is as follows:
`<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAdmin REDACTED
    ServerName REDACTED

    DocumentRoot /www/path1/html

    <Location />
        Auth_memCookie_Memcached_Configuration --SERVER=127.0.0.1:11211
        Auth_memCookie_Authoritative on
        Auth_memCookie_SessionTableSize "40"
        Auth_memCookie_CookieName "SimpleSAMLSessionID"
        AuthType Cookie
        AuthName "Login"
        ErrorDocument 401 "/simplesaml/module.php/memcookie/auth.php"
        Require all granted
    </Location>

    Alias /simplesaml /www/path1/simplesamlphp/www
    <Location /simplesaml>
        Require all granted
    </Location>

    <Location /manual>
        Require valid-user
    </Location>

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
        AllowOverride None
        Require all granted
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
    </Directory>

    ErrorLog /www/path1/logs/error.log
    LogLevel warn
    CustomLog /www/path1/logs/access.log combined


SSLCertificateFile /etc/letsencrypt/live/REDACTED/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/REDACTED/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
`

The path I'm trying to load is https://REDACTED/manual/ which is the protected directory above in the config. If I go to my /index.php, it loads properly (just a phpinfo() page) and if I put that same file at /123/index.php it also loads fine. It seems anything not protected is loading okay, but protected directories fail.

In my simplesamlphp/config/config.php I have baseurlpath defined as https://REDACTED/simplesaml/ and baseURL set to https://REDACTED/ which is the base URL for the site.

Finally, logging is set to debug and the following dumps into the syslog when I load the protected URL:
Mar 15 16:59:05 web01 simplesamlphp[2953]: 3 [36d9a5c5a9] SimpleSAML\Error\NotFound: The requested page 'https://REDACTED/manual' could not be found. The URL must at least contain a module name followed by a slash.
Mar 15 16:59:05 web01 simplesamlphp[2953]: 3 [36d9a5c5a9] Backtrace:
Mar 15 16:59:05 web01 simplesamlphp[2953]: 3 [36d9a5c5a9] 1 /www/path1/simplesamlphp/lib/SimpleSAML/Module.php:144 (SimpleSAML\Module::process)
Mar 15 16:59:05 web01 simplesamlphp[2953]: 3 [36d9a5c5a9] 0 /www/path1/simplesamlphp/www/module.php:9 (N/A)
Mar 15 16:59:05 web01 simplesamlphp[2953]: 3 [36d9a5c5a9] Error report with id 962c6585 generated.

**Comment by tvdijen** [comment]
Hmm, I don't see any obvious mistakes with that config.. What happens if you comment out baseurl and set baseurlpath back to the default `simplesaml/`?
Can you post the Apache access log so we can analyze the calls and redirects?

**Comment by hikarukujo** [comment]
So I deleted it all and tried to restart with a fresh SimpleSAMLphp and a fresh auth_memcookie install, but it seems the server is not putting the sessions into memcache at all anymore. When I attempt to check for rows in memcached, I get:
`stats slabs
STAT active_slabs 0
STAT total_malloced 0
END`

My apache config is:
`    <Location />
        Auth_memCookie_Memcached_Configuration "--SERVER=127.0.0.1:11211"
        Auth_memCookie_SetSessionHTTPHeader on
        Auth_memCookie_Authoritative on
        Auth_memCookie_SessionTableSize "100"
        Auth_memCookie_CookieName "SimpleSAML"
        AuthType Cookie
        AuthName "Login"
        ErrorDocument 401 "/simplesaml/module.php/memcookie/auth.php"
        Require all granted
    </Location>
`

And my stats page in simplesaml looks clear:
![Capture](https://user-images.githubusercontent.com/5297911/58515984-1f1dab80-816c-11e9-9edc-d7cdc11cdfe8.PNG)

Any ideas? I'm at a loss as to why it is being so stubborn, it just seems to refuse to work.

**Comment by tvdijen** [comment]
OK let's start over and try to pinpoint this...
What happens if you access the protected /manual? Are you being redirected to SimpleSAML? Can you trace what's actually happening using your Apache access log or your browser developer tools?

**Comment by hikarukujo** [comment]
So it does load a SimpleSAML page, but it is the error page which states:
```
Page not found
The given page was not found. The reason was: The URL must at least contain a module name followed by a slash.
```

In the corresponding logs I see in syslog:
```
May 29 13:20:59 SERVERNAME systemd-memcached-wrapper[24006]: <27 new auto-negotiating client connection
May 29 13:20:59 SERVERNAME systemd-memcached-wrapper[24006]: 27: Client using the ascii protocol
May 29 13:20:59 SERVERNAME systemd-memcached-wrapper[24006]: <27 get 342941da58adf22a48ddd2b1b537300e
May 29 13:20:59 SERVERNAME systemd-memcached-wrapper[24006]: >27 END
May 29 13:20:59 SERVERNAME systemd-memcached-wrapper[24006]: <27 quit
May 29 13:20:59 SERVERNAME systemd-memcached-wrapper[24006]: <27 connection closed.
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 7 [3669d8dc2e] Session: Valid session found with 'admin'.
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 7 [3669d8dc2e] Session: Valid session found with 'auth0-prod'.
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 7 [3669d8dc2e] Localization: using old system
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 7 [3669d8dc2e] Translate: Reading dictionary [/www/SITE.DOMAIN.COM/simplesamlphp/dictionaries/errors]
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 3 [3669d8dc2e] SimpleSAML\Error\NotFound: The requested page 'https://SITE.DOMAIN.COM/manual' could not be found. The URL must at least contain a module name followed by a slash.
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 3 [3669d8dc2e] Backtrace:
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 3 [3669d8dc2e] 1 /www/SITE.DOMAIN.COM/simplesamlphp/lib/SimpleSAML/Module.php:144 (SimpleSAML\Module::process)
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 3 [3669d8dc2e] 0 /www/SITE.DOMAIN.COM/simplesamlphp/www/module.php:9 (N/A)
May 29 13:20:59 SERVERNAME simplesamlphp[32069]: 3 [3669d8dc2e] Error report with id 88188526 generated.
```

And in the error.log for the web app:
```
[Wed May 29 13:20:59.784026 2019] [:error] [pid 32069] [client 208.184.104.163:21355] Auth_memCookie: memcached_get call failed: SUCCESS
[Wed May 29 13:20:59.784131 2019] [:warn] [pid 32069] [client 208.184.104.163:21355] Auth_memCookie: AuthSession 342941da58adf22a48ddd2b1b537300e not found: /www/SITE.DOMAIN.COM/html/manual
```

**Comment by tvdijen** [comment]
I'm at loss here.. It's sending the original request url to the error document??
I'd like to see your access.log as well to see what actually happens
